In [9]:
import pandas as pd
import re

In [3]:
#http://www.drafthistory.com/index.php/years/2010
nfl = pd.read_excel('/Users/caleboneel/Desktop/702FinalProject/draftdata.xlsx', skiprows = 1)

In [4]:
nfl['Snaps 2010'] = 0
nfl['Grade 2010'] = 0
nfl['Snaps 2011'] = 0
nfl['Grade 2011'] = 0
nfl['Snaps 2012'] = 0
nfl['Grade 2012'] = 0
nfl['Snaps 2013'] = 0
nfl['Grade 2013'] = 0
nfl['Snaps 2014'] = 0
nfl['Grade 2014'] = 0
nfl['Snaps 2015'] = 0
nfl['Grade 2015'] = 0
nfl['Snaps 2016'] = 0
nfl['Grade 2016'] = 0
nfl['Snaps 2017'] = 0
nfl['Grade 2017'] = 0
nfl['Snaps 2018'] = 0
nfl['Grade 2018'] = 0
nfl['Snaps 2019'] = 0
nfl['Grade 2019'] = 0

In [5]:
nfl.rename(columns={"Unnamed: 1": "Round", "Pick": "drop", "Player":"Pick"}, inplace = True)

In [6]:
nfl.drop(['Unnamed: 2', 'drop'], axis=1, inplace = True)

In [7]:
nfl

,Year,Round,Pick,Name,Team,Position,College,Snaps 2010,Grade 2010,Snaps 2011,...,Snaps 2015,Grade 2015,Snaps 2016,Grade 2016,Snaps 2017,Grade 2017,Snaps 2018,Grade 2018,Snaps 2019,Grade 2019
0,2010,1,1,Sam Bradford,Rams,QB,Oklahoma,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2010,1,2,Ndamukong Suh,Lions,DT,Nebraska,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2010,1,3,Gerald McCoy,Buccaneers,DT,Oklahoma,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2010,1,4,Trent Williams,Redskins,T,Oklahoma,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2010,1,5,Eric Berry,Chiefs,DB,Tennessee,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2539,2019,7,250,Austin Cutting,Vikings,C,Air Force,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2540,2019,7,251,Dakota Allen,Rams,LB,Texas Tech,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2541,2019,7,252,Ken Webster,Patriots,DB,Mississippi,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2542,2019,7,253,Jordan Brailford,Redskins,LB,Oklahoma State,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2543,2019,7,254,Caleb Wilson,Cardinals,TE,UCLA,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
nfl.to_csv('draft.csv', index=False)